-- Dishcovery Seed Recipes
-- Run in Supabase SQL Editor
-- Replace the email below with your Google login email

DO $$
DECLARE uid uuid;
BEGIN
  SELECT id INTO uid FROM auth.users LIMIT 1;

  INSERT INTO public.recipes (user_id, title, description, ingredients, steps, cuisine_type, prep_time, cook_time, serving_size, allergens, ai_nutrition_score, ai_difficulty_score, ai_authenticity_score, ai_calories_per_serving, ai_diet_tags, save_count, is_published) VALUES

  -- ITALIAN
  (uid, 'Classic Spaghetti Carbonara', 'A Roman classic with silky egg sauce and crispy pancetta. Rich, creamy, and ready in 20 minutes.', '[{"amount":"400","unit":"g","item":"spaghetti"},{"amount":"200","unit":"g","item":"pancetta or guanciale"},{"amount":"4","unit":"large","item":"eggs"},{"amount":"100","unit":"g","item":"Pecorino Romano"},{"amount":"2","unit":"cloves","item":"garlic"},{"amount":"1","unit":"tbsp","item":"black pepper"}]', '["Boil spaghetti in salted water until al dente.","Fry pancetta with garlic until crispy.","Whisk eggs with Pecorino and black pepper.","Toss hot pasta with pancetta, remove from heat.","Add egg mixture and toss vigorously until creamy.","Serve immediately with extra Pecorino."]', 'Italian', 5, 20, 4, '{"dairy","eggs"}', 7, 4, 9, 520, '{}', 42, true),

  (uid, 'Margherita Pizza', 'The original Neapolitan pizza with San Marzano tomatoes, fresh mozzarella, and basil. Simple perfection.', '[{"amount":"300","unit":"g","item":"pizza dough"},{"amount":"150","unit":"ml","item":"San Marzano tomato sauce"},{"amount":"200","unit":"g","item":"fresh mozzarella"},{"amount":"10","unit":"leaves","item":"fresh basil"},{"amount":"2","unit":"tbsp","item":"olive oil"},{"amount":"1","unit":"tsp","item":"sea salt"}]', '["Preheat oven to 250°C with pizza stone.","Stretch dough into 30cm circle.","Spread tomato sauce leaving 2cm border.","Tear mozzarella and distribute evenly.","Bake 10-12 minutes until crust is charred.","Top with fresh basil and drizzle olive oil."]', 'Italian', 15, 12, 2, '{"dairy","gluten"}', 6, 3, 10, 680, '{"vegetarian"}', 87, true),

  (uid, 'Creamy Tuscan Chicken', 'Pan-seared chicken in a sun-dried tomato cream sauce with spinach and parmesan. A restaurant-quality dish at home.', '[{"amount":"4","unit":"","item":"chicken breasts"},{"amount":"200","unit":"ml","item":"heavy cream"},{"amount":"100","unit":"g","item":"sun-dried tomatoes"},{"amount":"3","unit":"cups","item":"baby spinach"},{"amount":"4","unit":"cloves","item":"garlic"},{"amount":"80","unit":"g","item":"Parmesan"},{"amount":"1","unit":"tsp","item":"Italian seasoning"}]', '["Season chicken with salt, pepper, Italian seasoning.","Sear chicken 6 min per side until golden. Set aside.","Sauté garlic 1 minute in same pan.","Add cream, sun-dried tomatoes, simmer 3 minutes.","Add spinach until wilted, stir in Parmesan.","Return chicken to sauce, simmer 5 minutes."]', 'Italian', 10, 25, 4, '{"dairy"}', 8, 4, 8, 490, '{"gluten-free"}', 156, true),

  (uid, 'Risotto ai Funghi', 'Velvety Arborio rice cooked with mixed mushrooms, white wine, and Parmesan. The ultimate comfort food.', '[{"amount":"300","unit":"g","item":"Arborio rice"},{"amount":"400","unit":"g","item":"mixed mushrooms"},{"amount":"1","unit":"L","item":"warm chicken stock"},{"amount":"150","unit":"ml","item":"dry white wine"},{"amount":"1","unit":"large","item":"onion"},{"amount":"3","unit":"cloves","item":"garlic"},{"amount":"80","unit":"g","item":"Parmesan"},{"amount":"50","unit":"g","item":"butter"}]', '["Sauté mushrooms until golden. Set aside.","Soften onion and garlic in butter 5 minutes.","Add rice and toast 2 minutes.","Add wine and stir until absorbed.","Add stock ladle by ladle, stirring constantly 18 minutes.","Stir in mushrooms, Parmesan, and remaining butter."]', 'Italian', 10, 30, 4, '{"dairy"}', 7, 6, 9, 420, '{"vegetarian","gluten-free"}', 93, true),

  (uid, 'Tiramisu', 'The iconic Italian dessert with layers of espresso-soaked ladyfingers and mascarpone cream. No baking needed.', '[{"amount":"500","unit":"g","item":"mascarpone"},{"amount":"4","unit":"","item":"egg yolks"},{"amount":"100","unit":"g","item":"sugar"},{"amount":"300","unit":"ml","item":"espresso, cooled"},{"amount":"200","unit":"g","item":"ladyfingers"},{"amount":"30","unit":"ml","item":"rum (optional)"},{"amount":"2","unit":"tbsp","item":"cocoa powder"}]', '["Whisk egg yolks and sugar until pale and thick.","Fold in mascarpone until smooth.","Mix espresso with rum if using.","Dip ladyfingers briefly in espresso.","Layer ladyfingers in dish, top with cream.","Repeat layers, dust with cocoa.","Refrigerate 6 hours minimum."]', 'Italian', 30, 0, 8, '{"dairy","eggs","gluten"}', 5, 3, 10, 380, '{"vegetarian"}', 201, true),

  -- JAPANESE
  (uid, 'Chicken Teriyaki Bowl', 'Glossy teriyaki-glazed chicken thighs over steamed rice with sesame seeds and spring onions. A weeknight favourite.', '[{"amount":"600","unit":"g","item":"chicken thighs"},{"amount":"3","unit":"tbsp","item":"soy sauce"},{"amount":"2","unit":"tbsp","item":"mirin"},{"amount":"2","unit":"tbsp","item":"sake"},{"amount":"1","unit":"tbsp","item":"honey"},{"amount":"300","unit":"g","item":"short-grain rice"},{"amount":"2","unit":"stalks","item":"spring onions"},{"amount":"1","unit":"tbsp","item":"sesame seeds"}]', '["Cook rice according to package.","Mix soy, mirin, sake, honey for teriyaki sauce.","Pan-fry chicken skin-side down 5 minutes.","Flip and cook 4 more minutes.","Pour sauce over, cook 3 minutes until glazed.","Slice chicken and serve over rice.","Garnish with spring onions and sesame seeds."]', 'Japanese', 10, 20, 4, '{"soy","gluten"}', 7, 3, 9, 510, '{"dairy-free"}', 178, true),

  (uid, 'Miso Ramen', 'Rich miso broth with springy noodles, soft-boiled egg, corn, and bamboo shoots. Comfort in a bowl.', '[{"amount":"4","unit":"tbsp","item":"white miso paste"},{"amount":"1","unit":"L","item":"chicken or pork broth"},{"amount":"400","unit":"g","item":"ramen noodles"},{"amount":"4","unit":"","item":"soft-boiled eggs"},{"amount":"200","unit":"g","item":"corn kernels"},{"amount":"100","unit":"g","item":"bamboo shoots"},{"amount":"4","unit":"slices","item":"nori"},{"amount":"2","unit":"tbsp","item":"sesame oil"}]', '["Bring broth to simmer, whisk in miso paste.","Cook ramen noodles per package, drain.","Warm corn and bamboo shoots in broth.","Divide noodles into bowls.","Pour hot miso broth over noodles.","Top with halved eggs, corn, bamboo, nori.","Drizzle sesame oil to finish."]', 'Japanese', 10, 20, 4, '{"soy","gluten","eggs"}', 8, 4, 8, 560, '{"dairy-free"}', 134, true),

  (uid, 'Salmon Sashimi Salad', 'Fresh salmon over crispy mixed greens with ponzu dressing and avocado. Light, clean, and beautiful.', '[{"amount":"400","unit":"g","item":"sashimi-grade salmon"},{"amount":"2","unit":"","item":"avocados"},{"amount":"4","unit":"cups","item":"mixed greens"},{"amount":"1","unit":"","item":"cucumber, sliced"},{"amount":"3","unit":"tbsp","item":"ponzu sauce"},{"amount":"1","unit":"tbsp","item":"sesame oil"},{"amount":"1","unit":"tbsp","item":"sesame seeds"},{"amount":"2","unit":"tsp","item":"pickled ginger"}]', '["Slice salmon into thin sashimi pieces.","Slice avocado and cucumber.","Arrange greens on plates.","Top with salmon, avocado, cucumber.","Whisk ponzu with sesame oil for dressing.","Drizzle dressing over salad.","Garnish with sesame seeds and pickled ginger."]', 'Japanese', 15, 0, 4, '{"fish","soy"}', 9, 2, 9, 310, '{"gluten-free","dairy-free","low-calorie"}', 89, true),

  (uid, 'Vegetable Tempura', 'Light, crispy battered vegetables with a delicate dashi dipping sauce. Perfect as starter or snack.', '[{"amount":"1","unit":"","item":"sweet potato, sliced"},{"amount":"1","unit":"","item":"zucchini, sliced"},{"amount":"8","unit":"","item":"broccoli florets"},{"amount":"8","unit":"","item":"mushrooms"},{"amount":"150","unit":"g","item":"cold tempura flour"},{"amount":"200","unit":"ml","item":"ice cold water"},{"amount":"500","unit":"ml","item":"vegetable oil"},{"amount":"100","unit":"ml","item":"tentsuyu dipping sauce"}]', '["Heat oil to 175°C.","Mix flour and ice cold water briefly (lumps are fine).","Dip vegetables in batter.","Fry in batches 2-3 minutes until golden.","Drain on wire rack.","Serve immediately with dipping sauce."]', 'Japanese', 15, 15, 4, '{"gluten"}', 7, 5, 8, 280, '{"vegan","dairy-free"}', 67, true),

  (uid, 'Gyoza Dumplings', 'Crispy-bottomed pan-fried pork and cabbage dumplings with a tangy soy-vinegar dipping sauce.', '[{"amount":"300","unit":"g","item":"ground pork"},{"amount":"200","unit":"g","item":"cabbage, finely chopped"},{"amount":"30","unit":"","item":"gyoza wrappers"},{"amount":"2","unit":"cloves","item":"garlic"},{"amount":"1","unit":"tbsp","item":"ginger, grated"},{"amount":"2","unit":"tbsp","item":"soy sauce"},{"amount":"1","unit":"tbsp","item":"sesame oil"},{"amount":"2","unit":"tbsp","item":"vegetable oil"}]', '["Mix pork, cabbage, garlic, ginger, soy, sesame oil.","Place 1 tsp filling in each wrapper.","Fold and pleat edges to seal.","Heat oil in pan, add gyoza flat-side down.","Fry 2 minutes until bottoms are golden.","Add 60ml water, cover and steam 4 minutes.","Uncover, cook until water evaporates.","Serve with soy-vinegar dipping sauce."]', 'Japanese', 30, 15, 4, '{"soy","gluten"}', 6, 5, 9, 340, '{"dairy-free"}', 112, true),

  -- INDIAN
  (uid, 'Butter Chicken (Murgh Makhani)', 'Tender chicken in a velvety tomato-cream sauce fragrant with aromatic spices. The most loved Indian dish worldwide.', '[{"amount":"700","unit":"g","item":"chicken thighs"},{"amount":"400","unit":"g","item":"crushed tomatoes"},{"amount":"200","unit":"ml","item":"heavy cream"},{"amount":"50","unit":"g","item":"butter"},{"amount":"1","unit":"large","item":"onion"},{"amount":"4","unit":"cloves","item":"garlic"},{"amount":"1","unit":"tbsp","item":"garam masala"},{"amount":"1","unit":"tsp","item":"turmeric"},{"amount":"1","unit":"tsp","item":"chili powder"},{"amount":"1","unit":"tbsp","item":"ginger paste"}]', '["Marinate chicken in yogurt and spices 1 hour.","Grill or pan-fry chicken until charred. Set aside.","Sauté onion, garlic, ginger until golden.","Add spices and cook 1 minute.","Add tomatoes, simmer 15 minutes.","Blend sauce until smooth.","Add cream and butter, simmer 5 minutes.","Add chicken, cook 10 minutes.","Serve with naan or basmati rice."]', 'Indian', 20, 40, 4, '{"dairy"}', 8, 5, 10, 480, '{"gluten-free","halal"}', 245, true),

  (uid, 'Chana Masala', 'Bold and tangy chickpea curry with tomatoes, onions, and warming spices. A hearty vegan classic.', '[{"amount":"2","unit":"cans","item":"chickpeas"},{"amount":"400","unit":"g","item":"crushed tomatoes"},{"amount":"2","unit":"large","item":"onions"},{"amount":"4","unit":"cloves","item":"garlic"},{"amount":"1","unit":"tbsp","item":"ginger"},{"amount":"2","unit":"tsp","item":"cumin seeds"},{"amount":"1","unit":"tbsp","item":"coriander powder"},{"amount":"1","unit":"tsp","item":"garam masala"},{"amount":"1","unit":"tsp","item":"amchur powder"},{"amount":"2","unit":"tbsp","item":"oil"}]', '["Fry cumin seeds in oil until they splutter.","Add onions and cook until deep brown.","Add garlic and ginger, cook 2 minutes.","Add all spices, cook 1 minute.","Add tomatoes, cook until oil separates.","Add chickpeas and 200ml water.","Simmer 15 minutes. Mash some chickpeas.","Finish with garam masala and fresh coriander."]', 'Indian', 10, 30, 4, '{}', 9, 3, 9, 290, '{"vegan","vegetarian","gluten-free","dairy-free","halal"}', 189, true),

  (uid, 'Palak Paneer', 'Creamy spinach curry with golden cubes of fresh Indian cheese. A vegetarian comfort food staple.', '[{"amount":"500","unit":"g","item":"fresh spinach"},{"amount":"300","unit":"g","item":"paneer, cubed"},{"amount":"2","unit":"large","item":"onions"},{"amount":"3","unit":"cloves","item":"garlic"},{"amount":"1","unit":"tsp","item":"ginger"},{"amount":"100","unit":"ml","item":"cream"},{"amount":"1","unit":"tsp","item":"cumin"},{"amount":"1","unit":"tsp","item":"garam masala"},{"amount":"2","unit":"tbsp","item":"ghee"}]', '["Blanch spinach 2 minutes, blend smooth.","Pan-fry paneer cubes until golden, set aside.","Sauté onion in ghee until brown.","Add garlic, ginger, spices, cook 2 minutes.","Add spinach puree, simmer 5 minutes.","Stir in cream and season.","Add paneer and simmer 3 minutes.","Serve with naan or rice."]', 'Indian', 15, 25, 4, '{"dairy"}', 8, 4, 9, 380, '{"vegetarian","gluten-free","halal"}', 134, true),

  (uid, 'Dal Tadka', 'Comforting yellow lentil soup tempered with ghee, cumin, and garlic. Simple, nourishing, and delicious.', '[{"amount":"250","unit":"g","item":"yellow lentils (toor dal)"},{"amount":"2","unit":"medium","item":"tomatoes"},{"amount":"1","unit":"large","item":"onion"},{"amount":"4","unit":"cloves","item":"garlic"},{"amount":"1","unit":"tsp","item":"turmeric"},{"amount":"1","unit":"tsp","item":"cumin seeds"},{"amount":"2","unit":"dried","item":"red chilies"},{"amount":"3","unit":"tbsp","item":"ghee"},{"amount":"1","unit":"tsp","item":"mustard seeds"}]', '["Pressure cook lentils with turmeric and water until soft.","Mash lentils and add salt.","Heat ghee, add mustard seeds and cumin.","When they splutter, add dried chilies and garlic.","Add onion, cook until golden.","Add tomatoes, cook until soft.","Pour tadka over lentils and stir.","Simmer 5 minutes, garnish with coriander."]', 'Indian', 10, 30, 4, '{"dairy"}', 9, 2, 9, 260, '{"vegetarian","gluten-free","halal"}', 98, true),

  (uid, 'Lamb Biryani', 'Fragrant basmati rice layered with slow-cooked spiced lamb and caramelized onions. A celebration dish.', '[{"amount":"600","unit":"g","item":"lamb shoulder, cubed"},{"amount":"400","unit":"g","item":"basmati rice"},{"amount":"2","unit":"large","item":"onions, thinly sliced"},{"amount":"200","unit":"g","item":"yogurt"},{"amount":"4","unit":"cloves","item":"garlic"},{"amount":"1","unit":"tbsp","item":"ginger paste"},{"amount":"2","unit":"tsp","item":"biryani masala"},{"amount":"1","unit":"tsp","item":"saffron"},{"amount":"50","unit":"ml","item":"warm milk"},{"amount":"4","unit":"tbsp","item":"ghee"}]', '["Marinate lamb in yogurt and spices 2 hours.","Deep-fry onions until crispy golden.","Brown lamb in ghee, add water, simmer 45 minutes.","Par-cook rice until 70% done.","Steep saffron in warm milk.","Layer rice over lamb in pot.","Drizzle saffron milk and ghee.","Dum cook (sealed) on low heat 25 minutes.","Gently mix and serve with fried onions."]', 'Indian', 30, 90, 6, '{"dairy"}', 8, 8, 10, 580, '{"gluten-free","halal"}', 167, true),

  -- MEXICAN
  (uid, 'Street-Style Beef Tacos', 'Tender marinated carne asada in warm corn tortillas with fresh salsa, lime, and cilantro. Pure street food magic.', '[{"amount":"600","unit":"g","item":"beef skirt steak"},{"amount":"12","unit":"","item":"corn tortillas"},{"amount":"4","unit":"medium","item":"tomatoes"},{"amount":"1","unit":"","item":"white onion"},{"amount":"2","unit":"","item":"jalapeños"},{"amount":"1","unit":"bunch","item":"fresh cilantro"},{"amount":"2","unit":"","item":"limes"},{"amount":"3","unit":"cloves","item":"garlic"},{"amount":"2","unit":"tsp","item":"cumin"},{"amount":"1","unit":"tsp","item":"chili powder"}]', '["Marinate beef with garlic, cumin, chili, lime juice 1 hour.","Grill or pan-sear beef over high heat 4 min per side.","Rest 5 minutes, then slice thin against grain.","Dice tomatoes, onion, jalapeño for salsa.","Mix salsa with cilantro and lime juice.","Warm tortillas on dry pan.","Fill tortillas with beef and top with salsa.","Serve with lime wedges."]', 'Mexican', 20, 15, 4, '{"gluten"}', 7, 4, 10, 440, '{"dairy-free","gluten-free","halal"}', 203, true),

  (uid, 'Guacamole with Chips', 'Chunky, fresh guacamole with tomato, jalapeño, and lime. The ultimate party dip ready in 10 minutes.', '[{"amount":"4","unit":"ripe","item":"avocados"},{"amount":"2","unit":"medium","item":"tomatoes, diced"},{"amount":"1","unit":"small","item":"red onion, minced"},{"amount":"2","unit":"","item":"jalapeños, minced"},{"amount":"1","unit":"bunch","item":"cilantro"},{"amount":"2","unit":"","item":"limes, juiced"},{"amount":"1","unit":"tsp","item":"salt"},{"amount":"200","unit":"g","item":"tortilla chips"}]', '["Halve and pit avocados, scoop flesh.","Mash avocados to desired consistency.","Fold in tomatoes, onion, jalapeño.","Add cilantro and lime juice.","Season with salt to taste.","Cover tightly with plastic wrap touching surface.","Serve immediately with chips."]', 'Mexican', 10, 0, 6, '{}', 8, 1, 9, 220, '{"vegan","vegetarian","gluten-free","dairy-free"}', 156, true),

  (uid, 'Black Bean Enchiladas', 'Corn tortillas stuffed with spiced black beans and cheese, smothered in red chili sauce. Vegetarian crowd-pleaser.', '[{"amount":"2","unit":"cans","item":"black beans"},{"amount":"8","unit":"","item":"corn tortillas"},{"amount":"400","unit":"ml","item":"enchilada sauce"},{"amount":"250","unit":"g","item":"Mexican cheese blend"},{"amount":"1","unit":"","item":"onion, diced"},{"amount":"2","unit":"cloves","item":"garlic"},{"amount":"1","unit":"tsp","item":"cumin"},{"amount":"1","unit":"tsp","item":"smoked paprika"}]', '["Preheat oven to 190°C.","Sauté onion and garlic until soft.","Add beans, cumin, paprika, cook 5 minutes.","Warm tortillas to make pliable.","Fill each tortilla with bean mixture and cheese.","Roll and place seam-down in baking dish.","Pour enchilada sauce over top.","Sprinkle remaining cheese.","Bake 20 minutes until bubbly."]', 'Mexican', 15, 25, 4, '{"dairy","gluten"}', 8, 3, 8, 420, '{"vegetarian"}', 88, true),

  (uid, 'Chicken Quesadillas', 'Crispy flour tortillas filled with grilled chicken, peppers, and melted cheese. Quick and satisfying.', '[{"amount":"400","unit":"g","item":"chicken breast, cooked and shredded"},{"amount":"4","unit":"large","item":"flour tortillas"},{"amount":"200","unit":"g","item":"cheddar cheese, grated"},{"amount":"1","unit":"","item":"red pepper, sliced"},{"amount":"1","unit":"","item":"green pepper, sliced"},{"amount":"1","unit":"","item":"onion, sliced"},{"amount":"1","unit":"tsp","item":"cumin"},{"amount":"2","unit":"tbsp","item":"oil"}]', '["Sauté peppers and onion until soft.","Mix chicken with cumin and seasoning.","Heat pan over medium, brush with oil.","Place tortilla in pan, add cheese on half.","Top with chicken and peppers.","Fold tortilla over, cook 2-3 min per side.","Cut into wedges and serve with salsa and sour cream."]', 'Mexican', 10, 15, 4, '{"dairy","gluten"}', 7, 2, 8, 460, '{}', 145, true),

  (uid, 'Vegan Jackfruit Tacos', 'Slow-cooked pulled jackfruit with smoky chipotle sauce in corn tortillas. Meaty texture, fully plant-based.', '[{"amount":"2","unit":"cans","item":"young jackfruit"},{"amount":"12","unit":"","item":"corn tortillas"},{"amount":"2","unit":"tbsp","item":"chipotle in adobo"},{"amount":"1","unit":"can","item":"tomatoes"},{"amount":"1","unit":"","item":"onion"},{"amount":"3","unit":"cloves","item":"garlic"},{"amount":"1","unit":"tsp","item":"smoked paprika"},{"amount":"1","unit":"tsp","item":"cumin"},{"amount":"1","unit":"","item":"lime"},{"amount":"1","unit":"","item":"avocado"}]', '["Drain and rinse jackfruit, shred with forks.","Sauté onion and garlic until soft.","Add chipotle, tomatoes, spices, cook 2 minutes.","Add jackfruit and 100ml water.","Simmer 20 minutes, shredding as it cooks.","Warm corn tortillas.","Fill with jackfruit mixture.","Top with avocado slices and lime juice."]', 'Mexican', 10, 25, 4, '{}', 8, 3, 7, 290, '{"vegan","vegetarian","gluten-free","dairy-free"}', 77, true),

  -- MEDITERRANEAN
  (uid, 'Greek Chicken Souvlaki', 'Lemon-herb marinated chicken skewers with tzatziki, warm pita, and fresh salad. Summer on a plate.', '[{"amount":"600","unit":"g","item":"chicken breast, cubed"},{"amount":"4","unit":"","item":"pita breads"},{"amount":"200","unit":"g","item":"Greek yogurt"},{"amount":"1","unit":"","item":"cucumber, grated"},{"amount":"4","unit":"cloves","item":"garlic"},{"amount":"1","unit":"","item":"lemon"},{"amount":"3","unit":"tbsp","item":"olive oil"},{"amount":"1","unit":"tbsp","item":"dried oregano"},{"amount":"2","unit":"tsp","item":"dried thyme"}]', '["Marinate chicken with olive oil, lemon, garlic, herbs 2 hours.","Make tzatziki: mix yogurt, cucumber, garlic, dill.","Thread chicken on skewers.","Grill 12-15 minutes, turning occasionally.","Warm pitas on grill.","Serve souvlaki in pita with tzatziki and salad."]', 'Mediterranean', 20, 15, 4, '{"dairy","gluten"}', 8, 3, 9, 420, '{"halal"}', 167, true),

  (uid, 'Shakshuka', 'Eggs poached in a spiced tomato and pepper sauce. A Middle Eastern breakfast-for-any-time classic.', '[{"amount":"6","unit":"large","item":"eggs"},{"amount":"400","unit":"g","item":"crushed tomatoes"},{"amount":"2","unit":"","item":"red peppers"},{"amount":"1","unit":"large","item":"onion"},{"amount":"4","unit":"cloves","item":"garlic"},{"amount":"1","unit":"tsp","item":"cumin"},{"amount":"1","unit":"tsp","item":"smoked paprika"},{"amount":"1/2","unit":"tsp","item":"chili flakes"},{"amount":"3","unit":"tbsp","item":"olive oil"},{"amount":"100","unit":"g","item":"feta cheese"}]', '["Sauté onion and peppers in olive oil 8 minutes.","Add garlic and spices, cook 1 minute.","Add tomatoes, simmer 10 minutes.","Make 6 wells in sauce.","Crack one egg into each well.","Cover and cook 5-8 minutes until whites set.","Crumble feta on top.","Serve with crusty bread."]', 'Mediterranean', 10, 25, 4, '{"dairy","eggs"}', 8, 3, 9, 290, '{"vegetarian","gluten-free"}', 198, true),

  (uid, 'Hummus with Roasted Vegetables', 'Silky smooth homemade hummus topped with roasted seasonal vegetables and dukkah. Perfect mezze dish.', '[{"amount":"2","unit":"cans","item":"chickpeas"},{"amount":"4","unit":"tbsp","item":"tahini"},{"amount":"2","unit":"","item":"lemons, juiced"},{"amount":"3","unit":"cloves","item":"garlic"},{"amount":"4","unit":"tbsp","item":"olive oil"},{"amount":"1","unit":"","item":"zucchini, diced"},{"amount":"1","unit":"","item":"red pepper, diced"},{"amount":"1","unit":"","item":"eggplant, diced"},{"amount":"1","unit":"tsp","item":"dukkah spice blend"}]', '["Roast vegetables at 200°C for 25 minutes.","Blend chickpeas, tahini, lemon, garlic until very smooth.","Stream in olive oil while blending.","Add ice water to achieve creamy texture.","Spread hummus on plate, create a well.","Top with roasted vegetables.","Drizzle olive oil and sprinkle dukkah."]', 'Mediterranean', 15, 25, 4, '{"sesame"}', 9, 2, 9, 310, '{"vegan","vegetarian","gluten-free","dairy-free"}', 143, true),

  (uid, 'Falafel Wrap', 'Crispy chickpea falafel in warm flatbread with tahini, pickles, and fresh vegetables. Street food favourite.', '[{"amount":"400","unit":"g","item":"dried chickpeas, soaked overnight"},{"amount":"1","unit":"large","item":"onion"},{"amount":"4","unit":"cloves","item":"garlic"},{"amount":"2","unit":"tsp","item":"cumin"},{"amount":"2","unit":"tsp","item":"coriander"},{"amount":"4","unit":"","item":"flatbreads"},{"amount":"100","unit":"g","item":"tahini"},{"amount":"2","unit":"","item":"tomatoes"},{"amount":"1","unit":"","item":"cucumber"},{"amount":"500","unit":"ml","item":"oil for frying"}]', '["Blend soaked chickpeas with onion, garlic, spices until coarse.","Form into balls or patties.","Refrigerate 1 hour.","Deep fry at 175°C for 4 minutes until golden.","Make tahini sauce with lemon and water.","Warm flatbreads.","Fill with falafel, vegetables, and tahini sauce."]', 'Mediterranean', 30, 15, 4, '{"sesame","gluten"}', 9, 5, 10, 490, '{"vegan","vegetarian","dairy-free"}', 134, true),

  (uid, 'Grilled Sea Bass', 'Whole sea bass grilled with lemon, capers, and herbs. Clean, elegant, and ready in 20 minutes.', '[{"amount":"2","unit":"whole","item":"sea bass (500g each)"},{"amount":"2","unit":"","item":"lemons"},{"amount":"3","unit":"cloves","item":"garlic"},{"amount":"2","unit":"tbsp","item":"capers"},{"amount":"4","unit":"tbsp","item":"olive oil"},{"amount":"1","unit":"bunch","item":"fresh parsley"},{"amount":"1","unit":"bunch","item":"fresh thyme"},{"amount":"1","unit":"tsp","item":"sea salt"}]', '["Score fish 3 times on each side.","Stuff cavity with lemon slices, garlic, herbs.","Brush with olive oil and season with salt.","Grill on high heat 5-7 minutes per side.","Make caper dressing with oil, capers, lemon juice.","Rest fish 3 minutes.","Serve drizzled with caper dressing."]', 'Mediterranean', 10, 15, 4, '{"fish"}', 9, 4, 9, 280, '{"gluten-free","dairy-free"}', 78, true),

  -- MIXED / OTHER
  (uid, 'Korean Bibimbap', 'Colorful rice bowl with seasoned vegetables, gochujang, and a fried egg. A balanced Korean classic.', '[{"amount":"400","unit":"g","item":"short-grain rice"},{"amount":"4","unit":"","item":"eggs"},{"amount":"200","unit":"g","item":"spinach"},{"amount":"2","unit":"","item":"carrots, julienned"},{"amount":"200","unit":"g","item":"mushrooms"},{"amount":"200","unit":"g","item":"bean sprouts"},{"amount":"4","unit":"tbsp","item":"gochujang"},{"amount":"2","unit":"tbsp","item":"sesame oil"},{"amount":"2","unit":"tbsp","item":"soy sauce"}]', '["Cook rice.","Blanch spinach, squeeze dry, season with sesame oil.","Sauté carrots, mushrooms separately with soy sauce.","Blanch bean sprouts, season.","Fry eggs sunny-side up.","Divide rice into bowls.","Arrange vegetables in sections over rice.","Top with fried egg and gochujang.","Mix everything before eating."]', 'Korean', 20, 30, 4, '{"soy","eggs"}', 9, 4, 10, 490, '{"vegetarian","dairy-free"}', 167, true),

  (uid, 'Thai Green Curry', 'Creamy coconut milk curry with green curry paste, vegetables, and jasmine rice. Aromatic and vibrant.', '[{"amount":"400","unit":"ml","item":"coconut milk"},{"amount":"3","unit":"tbsp","item":"green curry paste"},{"amount":"500","unit":"g","item":"chicken breast"},{"amount":"1","unit":"","item":"zucchini"},{"amount":"1","unit":"","item":"red pepper"},{"amount":"100","unit":"g","item":"baby spinach"},{"amount":"2","unit":"stalks","item":"lemongrass"},{"amount":"4","unit":"leaves","item":"kaffir lime"},{"amount":"2","unit":"tbsp","item":"fish sauce"},{"amount":"300","unit":"g","item":"jasmine rice"}]', '["Fry curry paste in coconut cream 2 minutes.","Add chicken and stir-fry until sealed.","Add remaining coconut milk, lemongrass, lime leaves.","Simmer 10 minutes.","Add vegetables and fish sauce.","Cook 5 more minutes until vegetables tender.","Remove lemongrass and lime leaves.","Serve over jasmine rice with fresh basil."]', 'Thai', 10, 25, 4, '{"fish"}', 8, 4, 9, 520, '{"gluten-free","dairy-free"}', 189, true),

  (uid, 'Vietnamese Pho', 'Fragrant beef broth with rice noodles, thinly sliced beef, and fresh herbs. Soul-warming comfort food.', '[{"amount":"1","unit":"kg","item":"beef bones"},{"amount":"400","unit":"g","item":"beef sirloin, thinly sliced"},{"amount":"400","unit":"g","item":"pho rice noodles"},{"amount":"1","unit":"large","item":"onion, charred"},{"amount":"4","unit":"cm","item":"ginger, charred"},{"amount":"3","unit":"","item":"star anise"},{"amount":"2","unit":"","item":"cinnamon sticks"},{"amount":"4","unit":"cloves","item":"cloves"},{"amount":"3","unit":"tbsp","item":"fish sauce"},{"amount":"1","unit":"bunch","item":"bean sprouts, basil, lime"}]', '["Char onion and ginger over flame.","Boil bones 10 minutes, drain and rinse.","Simmer bones with charred veg and spices 3 hours.","Strain broth, season with fish sauce.","Soak noodles in hot water 20 minutes.","Place noodles in bowls.","Lay raw beef slices over noodles.","Pour boiling hot broth over (it cooks the beef).","Serve with bean sprouts, herbs, lime."]', 'Vietnamese', 30, 180, 4, '{"fish"}', 9, 6, 10, 410, '{"gluten-free","dairy-free"}', 123, true),

  (uid, 'Moroccan Lamb Tagine', 'Fall-apart lamb with preserved lemon, olives, and fragrant ras el hanout. Slow-cooked North African perfection.', '[{"amount":"800","unit":"g","item":"lamb shoulder"},{"amount":"1","unit":"preserved","item":"lemon"},{"amount":"100","unit":"g","item":"green olives"},{"amount":"2","unit":"large","item":"onions"},{"amount":"4","unit":"cloves","item":"garlic"},{"amount":"2","unit":"tsp","item":"ras el hanout"},{"amount":"1","unit":"tsp","item":"turmeric"},{"amount":"1","unit":"tsp","item":"ginger"},{"amount":"400","unit":"ml","item":"lamb stock"},{"amount":"2","unit":"tbsp","item":"olive oil"}]', '["Brown lamb in batches in olive oil.","Soften onions and garlic 5 minutes.","Add all spices and stir 1 minute.","Return lamb, add stock.","Bring to boil, reduce heat.","Cover and simmer 1.5 hours.","Add preserved lemon and olives.","Cook 30 more minutes until lamb falls apart.","Serve with couscous and harissa."]', 'Moroccan', 20, 120, 6, '{}', 8, 5, 9, 460, '{"gluten-free","dairy-free","halal"}', 89, true),

  (uid, 'Avocado Toast with Poached Eggs', 'Creamy avocado on sourdough with perfectly poached eggs, chili flakes, and everything bagel seasoning.', '[{"amount":"4","unit":"slices","item":"sourdough bread"},{"amount":"3","unit":"ripe","item":"avocados"},{"amount":"4","unit":"large","item":"eggs"},{"amount":"1","unit":"","item":"lemon"},{"amount":"1","unit":"tsp","item":"chili flakes"},{"amount":"1","unit":"tsp","item":"everything bagel seasoning"},{"amount":"2","unit":"tbsp","item":"white vinegar"},{"amount":"2","unit":"tbsp","item":"olive oil"}]', '["Toast sourdough until golden.","Mash avocado with lemon juice and salt.","Bring water with vinegar to gentle simmer.","Crack each egg into a small cup.","Create whirlpool, gently slide in eggs.","Poach 3-4 minutes.","Spread avocado on toast.","Top with poached eggs.","Sprinkle chili flakes and bagel seasoning."]', 'American', 10, 10, 4, '{"eggs","gluten","dairy"}', 8, 4, 7, 390, '{"vegetarian","dairy-free"}', 278, true),

  (uid, 'Beef Bulgogi', 'Korean marinated beef with sweet-savory soy sauce, served with rice and kimchi. A BBQ favourite.', '[{"amount":"600","unit":"g","item":"beef sirloin, thinly sliced"},{"amount":"4","unit":"tbsp","item":"soy sauce"},{"amount":"2","unit":"tbsp","item":"sugar"},{"amount":"1","unit":"tbsp","item":"sesame oil"},{"amount":"1","unit":"","item":"Asian pear, grated"},{"amount":"4","unit":"cloves","item":"garlic"},{"amount":"1","unit":"tbsp","item":"ginger"},{"amount":"300","unit":"g","item":"steamed rice"},{"amount":"2","unit":"stalks","item":"spring onions"}]', '["Combine soy, sugar, sesame oil, pear, garlic, ginger.","Marinate beef at least 1 hour.","Heat grill pan or BBQ to very high heat.","Cook beef in batches 2-3 minutes per side.","Rest briefly.","Serve over rice with spring onions and sesame seeds."]', 'Korean', 15, 15, 4, '{"soy"}', 7, 3, 10, 440, '{"dairy-free","gluten-free"}', 156, true),

  (uid, 'Lentil Soup', 'Hearty red lentil soup with cumin, turmeric, and a squeeze of lemon. Nutritious, easy, and filling.', '[{"amount":"300","unit":"g","item":"red lentils"},{"amount":"1","unit":"large","item":"onion"},{"amount":"4","unit":"cloves","item":"garlic"},{"amount":"2","unit":"medium","item":"carrots"},{"amount":"2","unit":"medium","item":"tomatoes"},{"amount":"1","unit":"tsp","item":"cumin"},{"amount":"1","unit":"tsp","item":"turmeric"},{"amount":"1","unit":"tsp","item":"smoked paprika"},{"amount":"1.5","unit":"L","item":"vegetable stock"},{"amount":"2","unit":"","item":"lemons"}]', '["Sauté onion and garlic in oil 5 minutes.","Add carrots and cook 3 minutes.","Add spices and stir 1 minute.","Add lentils, tomatoes, and stock.","Bring to boil, simmer 25 minutes until lentils dissolve.","Blend half the soup for creamy texture.","Season and add lemon juice.","Serve with crusty bread and extra lemon."]', 'Mediterranean', 10, 30, 6, '{}', 9, 2, 8, 240, '{"vegan","vegetarian","gluten-free","dairy-free","halal","low-calorie"}', 112, true),

  (uid, 'Fish and Chips', 'Crispy beer-battered cod with thick-cut chips and mushy peas. A British classic done right.', '[{"amount":"4","unit":"fillets","item":"cod (200g each)"},{"amount":"4","unit":"large","item":"potatoes"},{"amount":"150","unit":"g","item":"plain flour"},{"amount":"200","unit":"ml","item":"cold beer"},{"amount":"1","unit":"tsp","item":"baking powder"},{"amount":"200","unit":"g","item":"frozen peas"},{"amount":"2","unit":"tbsp","item":"butter"},{"amount":"1","unit":"L","item":"vegetable oil"},{"amount":"1","unit":"","item":"lemon"}]', '["Cut potatoes into thick chips, soak in water 30 mins.","Heat oil to 160°C, par-fry chips 8 minutes. Set aside.","Make batter: flour, baking powder, beer, whisk until smooth.","Increase oil to 180°C.","Pat fish dry, coat in batter.","Fry fish 6-8 minutes until golden.","Fry chips again at 180°C until crispy.","Crush peas with butter, season.","Serve with lemon and tartare sauce."]', 'British', 30, 30, 4, '{"fish","gluten"}', 6, 5, 10, 680, '{"dairy-free"}', 145, true),

  (uid, 'Mango Sticky Rice', 'Creamy coconut sticky rice with fresh mango slices and toasted sesame. A Thai dessert dream.', '[{"amount":"300","unit":"g","item":"glutinous rice"},{"amount":"400","unit":"ml","item":"coconut milk"},{"amount":"3","unit":"tbsp","item":"sugar"},{"amount":"1","unit":"tsp","item":"salt"},{"amount":"3","unit":"ripe","item":"mangoes"},{"amount":"2","unit":"tbsp","item":"toasted sesame seeds"},{"amount":"2","unit":"pandan","item":"leaves (optional)"}]', '["Soak glutinous rice 4 hours, then steam 25 minutes.","Heat coconut milk with sugar and salt until dissolved.","Pour 2/3 of coconut sauce over hot rice.","Stir and let absorb 10 minutes.","Slice mangoes.","Plate sticky rice with mango slices alongside.","Drizzle remaining coconut sauce over.","Sprinkle with toasted sesame seeds."]', 'Thai', 30, 30, 4, '{"sesame"}', 6, 4, 10, 480, '{"vegan","vegetarian","gluten-free","dairy-free"}', 98, true);

END $$;
